#!/usr/bin/with-contenv sh

if [[ -z $DEBUG ]]; then
  : ${VARNISH_NCSA_FORMAT:='%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i"'}
  varnishncsa -F "${VARNISH_NCSA_FORMAT}"
else
  echo "Debug logging enabled"
  varnishlog
fi
